//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OlympiaApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vong1
    {
        public int ID { get; set; }
        public string CauHoi { get; set; }
        public string DapAn { get; set; }
        public Nullable<int> Khoa { get; set; }
        public string Pro1 { get; set; }
        public string Pro2 { get; set; }
        public string Pro3 { get; set; }
        public string Pro4 { get; set; }
        public string Pro5 { get; set; }
    }
}
